version: '3.7'

services:
  yalcs:
    build: 
      context: .
      target: builder
    image: yalcs:builder      
    container_name: yalcs_dev
    ports:
      - 2040:2040
      - 2041:2041
    volumes:
      - .:/home/node
      - loader_deps:/home/node/loader/node_modules
      - server_deps:/home/node/server/node_modules
      - web_deps:/home/node/web/node_modules
    command: /home/node/docker-entrypoint.sh

volumes:
  loader_deps:
    driver: local
  server_deps:
    driver: local
  web_deps:
    driver: local
  
